[tool.poetry]
name = "coralsnake"
version = "0.1.0"
description = "A minimalistic FHIR server for resources as files"
authors = ["Ilya Beda <ilya@beda.software>", "Aleksandr Pavlushkin <aleksandr.p@beda.software>"]
readme = "README.md"
homepage = "https://github.com/beda-software/coralsnake/"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.112.1"
uvicorn = "^0.30.6"
pyyaml = "^6.0.2"

[tool.poetry.dev-dependencies]
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "UP", "I"]